services:
  # Database
  - type: pserv
    name: mongodb
    env: docker
    dockerImage: mongo
    disk:
      name: mongo-data
      mountPath: /data/db
      sizeGB: 1

  # Eureka Server
  - type: web
    name: service-registry
    env: docker
    rootDir: ./service-registry
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /

  # Public-facing Services
  - type: web
    name: api-gateway
    env: docker
    rootDir: ./api-gateway
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: eureka.client.service-url.defaultZone
        value: http://service-registry:8761/eureka/

  - type: web
    name: dashboard-service
    env: docker
    rootDir: ./dashboard-service
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: eureka.client.service-url.defaultZone
        value: http://service-registry:8761/eureka/

  # Backend Private Services
  - type: pserv
    name: employee-service
    env: docker
    rootDir: ./employee-service
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: spring.data.mongodb.uri
        fromService:
          type: pserv
          name: mongodb
          property: connectionString
      - key: eureka.client.service-url.defaultZone
        value: http://service-registry:8761/eureka/

  - type: pserv
    name: leave-service
    env: docker
    rootDir: ./leave-service
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: spring.data.mongodb.uri
        fromService:
          type: pserv
          name: mongodb
          property: connectionString
      - key: eureka.client.service-url.defaultZone
        value: http://service-registry:8761/eureka/

  - type: pserv
    name: notification-service
    env: docker
    rootDir: ./notification-service
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: spring.mail.username
        sync: false
      - key: spring.mail.password
        sync: false
      - key: eureka.client.service-url.defaultZone
        value: http://service-registry:8761/eureka/
  
  - type: pserv
    name: ai-analyzer-service
    env: docker
    rootDir: ./ai-analyzer-service
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: eureka.client.service-url.defaultZone
        value: http://service-registry:8761/eureka/